include: 
  - packages.base
  - packages.crashplan
  - packages.firefox
  - packages.google-chrome
  - packages.handbrake
  - packages.libreoffice
  - packages.network-tools
  - packages.slim
  - packages.system-tools
  - packages.xfce
  - packages.xorg
